### PR TITLE
Making `all` validator chainable (isRequired)

### PR DESCRIPTION
**Pull request by Aldredcz**
@jquense Hello Jason, I miss possibility of `.isRequired` when creating propType using `all` helper, so I added it. Could you review and publish please? :) Thanks.

### CODE REVIEW

**Comment by taion** [comment]
LGTM

**Comment by taion** [comment]
Actually, please add a quick test case here.

**Comment by Aldredcz** [comment]
@taion Added.

**Comment by taion** [comment]
LGTM

**Comment by taion** [comment]
Released on v0.3.1

**Comment by Aldredcz** [comment]
Thx

**Pull request merged**
