### PR TITLE
Inception

### PR DESCRIPTION
**Pull request by AlexKVal**
All works. 
Linting, building, testing and even coverage.

Every checker placed into different file 
to make it possible to import only specific checkers.

### CODE REVIEW

**Comment by jquense** [comment]
looks awesome!

**Comment by AlexKVal** [comment]
TravisCI doesn't start

**Comment by AlexKVal** [comment]
I have no rights in the main repo. Can you take a look there, please ?

**Comment by AlexKVal** [comment]
I've enabled it for my fork
(if was green, then I deleted branch)
Yay.

**Comment by mathieumg** [comment]
Awesome, thanks for this! :tada:

**Pull request merged**
