### PR TITLE
Update karma-coverage dev dependency

### PR DESCRIPTION
**Pull request by AlexKVal**

### CODE REVIEW

**Comment by jquense** [comment]
are there breaking changes on the eslint config defaults that affect us? LGTM otherwise

**Comment by AlexKVal** [comment]
There are several commits in `eslint-config-defaults` that brings `3`=>`4`
[One of them](https://github.com/walmartlabs/eslint-config-defaults/commit/8b90843ab3a5203c46612216169b25bd0d6eb73d)
And I don't like it because of at least [that line](https://github.com/walmartlabs/eslint-config-defaults/commit/8b90843ab3a5203c46612216169b25bd0d6eb73d#diff-0f4e06cb563662e6476a33a35426bedeR38)

``` diff
-    "no-eval": 2,
+    "no-eval": 0,
```

I've checked:
`eslint@0.24` had warning about `eval`,
`eslint-config-defaults@3.1.0` also had it,
but this new version `4.0.1` has it disabled.

I believe there are other disabled rules too.

It seems that `eslint-config-defaults` package is no more `eslint@0.24` defaults :sweat: 
And we had to decide something with `eslint` configuration.

I've changed commit to reflect only `karma-coverage` update.

## 

Sorry about it. I was sure that guys in `eslint-config-defaults` won't break `eslint@0.24` defaults.

And now I really don't understand what is the difference between
https://github.com/walmartlabs/eslint-config-defaults#full-configurations
- `defaults` - The default ESLint config
  and
- `defaults/configurations/off` - Turns off all rules. This will be ESLint's default after 1.0.0

**Comment by jquense** [comment]
I mean we don't need to be tightly stuck to the 0.24 defaults, I was more just wondering what the breaking change was since the version was making a major bump.

**Comment by AlexKVal** [comment]
There are enough, such as disabling `eval()` warning, changes
https://github.com/walmartlabs/eslint-config-defaults/commit/8b90843ab3a5203c46612216169b25bd0d6eb73d
It's not a trivial task to compare them all - rule by rule with what was used by `R-B` with `eslint@0.24`.

## 

The idea with `eslint-config-defaults` was that they provide the basis that was used by `R-B`.
After `4.0.1` version this is not true and we have to decide something with `eslint` configuration.

**Comment by AlexKVal** [comment]
I've checked `defaults/configurations/airbnb` and `defaults/configurations/walmart/es6-react`
`100` and `99` warnings only in this small project :smile: 
Though they are mostly in tests.

**Comment by AlexKVal** [comment]
just numbers:

``` sh
> eslint src
```

`defaults/configurations/airbnb`
✖ 15 problems (13 errors, 2 warnings)

`defaults/configurations/walmart/es6-react`
✖ 45 problems (45 errors, 0 warnings)

**Comment by AlexKVal** [comment]
I merge this `karma-coverage` update.
`eslint` issue continues in #9

**Pull request merged**
