### PR TITLE
[WIP] Update to babel-6

### PR DESCRIPTION
**Pull request by AlexKVal**
(next one will be about `react-0.14`. I don't want to mix them)

### CODE REVIEW

**Comment by AlexKVal** [comment]
pff... I forgot about eslint.
will fix it in an hour.

**Comment by jquense** [comment]
this definitely would need to go into `0.28-rc` as I am not confident the transpiling doesn't break a lot of things. For instance Common JS module transpilation has a breaking change. I am _very_ reticent to upgrade yet, since there are still a bunch of outstanding big issues

**Comment by AlexKVal** [comment]
No problem at all. 
`babel6` updates will go to next breaking version of `react-prop-types` and `R-B` `package.json` will just point to that version whenever it is ready.
What do you think ?

**Comment by jquense** [comment]
sorry I got my branches wrong again :P I mean we can point RB to next version whenever yuo think it works, I was just sending some caution that more subtle things may break!

**Comment by AlexKVal** [comment]
Got it. Thank you for the cautions. I will check every change thorougly and report about it.

**Comment by AlexKVal** [comment]
It seems there is an issue with `karma` + `webpack conifg files in es6` + `babel-loader@6`
screen shot 2015-11-05 at 10 02 25 am

When I use `webpack config file` in `es5` - tests are green too.

But `isparta` (and hence the whole `coverage` path doesn't work yet with `babel6`).

Then I'll wait till upstream dependencies are updated for `babel@6`

**Comment by taion** [comment]
I don't think I'm totally comfortable with breaking the current style of imports for all of our non-ES6 users.

@jquense Are you aware of any Babel transforms that bring back the old behavior when there's a single default export?

**Comment by jquense** [comment]
not yet, but we should find one, asking CJS users to user `theimport.default` for everything is a non-starter for me,

so far the only thing I've gotten from the babel team was "use both `export` and `module.exports`" which is silly.

**Comment by AlexKVal** [comment]
Then let's mark this PR with milestone smth like 'babel@6 changed import', or 'some future version'
or we can just close it for now. No problem at all.
What do you think ?

**Comment by taion** [comment]
Your call. We can't stay on Babel 5.x forever.

**Comment by AlexKVal** [comment]
I believe it is not a relevant patch already and I won't continue on this, so I just close it :)

**Pull request closed without merging**
