### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by AlexKVal**

### CODE REVIEW

**Comment by jquense** [comment]
are we upgrading our eslintrc with the bumps to 1.0.0, which disables all rules by default?

**Comment by AlexKVal** [comment]
I am sorry. Probably I don't understand what is about your concern :cold_sweat: 
we have enabled rules what we need here https://github.com/react-bootstrap/react-prop-types/blob/master/.eslintrc

**Comment by AlexKVal** [comment]
We did almost exactly the same in `react-bootstrap` by this https://github.com/react-bootstrap/react-bootstrap/pull/1093
here [package.json:R58](https://github.com/react-bootstrap/react-bootstrap/pull/1093/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R58)

**Comment by taion** [comment]
Oh crap.

**Comment by jquense** [comment]
I am asking about both. not all the rules are not on by default whereas our `.eslintrc`'s only turn on/off s small set of the normal rules that are on. so more then likely the vast amount of lint rules we had are now off

**Comment by taion** [comment]
That was definitely just a mistake on my part.

**Comment by AlexKVal** [comment]
`eslint` defaults back again :tada: :smile: 
I fixed this PR.

**Comment by AlexKVal** [comment]
@jquense thank you for pointing to this :cherries: 
(It was my 'monkey' copy/past from 'R-B'.)

**Comment by taion** [comment]
:shipit:

**Pull request merged**
